WIDTH = 1800
HEIGHT = 900
CENTER = (WIDTH / 2, HEIGHT / 2)

# I don't know what to call this. The distance between the inside and outside of the torus.
TORUS_SIZE = 186

TORUS_OUTER_HEIGHT = 900
TORUS_OUTER_WIDTH = 1280

TORUS_INNER_HEIGHT = TORUS_OUTER_HEIGHT - TORUS_SIZE  * 2
TORUS_INNER_WIDTH = TORUS_OUTER_WIDTH - TORUS_SIZE * 2
TORUS_INNER_RADIUS = min(TORUS_INNER_HEIGHT, TORUS_INNER_WIDTH) // 2

RING_HEIGHT = TORUS_OUTER_HEIGHT - 66
RING_WIDTH = TORUS_OUTER_WIDTH - 66
RING_RADIUS = min(RING_HEIGHT, RING_WIDTH) // 2

NUM_BOXES = 100
