WIDTH = 1800
HEIGHT = 900
CENTER = (WIDTH / 2, HEIGHT / 2)

TORUS_OUTER_HEIGHT = 900
TORUS_OUTER_WIDTH = 1280

RING_HEIGHT = TORUS_OUTER_HEIGHT - 66
RING_WIDTH = TORUS_OUTER_WIDTH - 66
RING_RADIUS = min(RING_HEIGHT, RING_WIDTH) // 2

NUM_BOXES = 100
